### ISSUE TITLE
Support strings with \

### ISSUE THREAD

**Issue by omerlh** [moov-io/bai2#114]
Bai2 Version: `latest, compled from main`

**What were you trying to do?**
I have BAI2 (actually BAI3) file from my bank and it fails validation on lines with string containing `\` which is end of line of BAI2. For example - dates like 13/05/24. 

On a side note, I got this parser to read my file by changing the version on the first line of the file...

**What did you expect to see?**
File parsed correctly 

**What did you see?**
Errors like:
```
Error: ERROR parsing account on line 218 (unable to read record type 04)
```

**How can we reproduce the problem?**
Create a BAI2 file with a text containing `\`

Thanks!

**Comment by wokkaflokka** [comment]
@adamdecaf my interpretation is yes, they are the same report. 

I had encountered the same behavior and noted it [here](https://moov-io.slack.com/archives/C03A3QA71G8/p1710342950749339?thread_ts=1710192960.222329&cid=C03A3QA71G8) in the moov slack.

I finally ran into a file with data like this in production, and have been motivated to take another pass at addressing this. PR incoming.

**Comment by wokkaflokka** [comment]
@omerlh would it be possible for you to provide a sample file that highlights the failure and is representative of the data you need to parse? I have a proposed fix here and could use this test case to ensure it covers your scenario.

**Comment by omerlh** [comment]
Sorry for not looking into open issues! Yes, it seems like the same issue... 

@wokkaflokka uploading a file will be challenging but I am happy to test a branch locally if you want :)

**Comment by omerlh** [comment]
I just tested the latest code on main and it still failing with the same error for this line:

```
88,<redacted>,<redacted>=/<redacted>/<redacted>
```

**Comment by wokkaflokka** [comment]
@omerlh  I understand that difficulty. Would it be possible to take a file and scrub it or extract a relevant piece of it? The snippet you post is useful -- if you could create a representative file, even if it's only 1 transaction, it would help to write a test around.

**Comment by omerlh** [comment]
Sorry - my bad! I just tested it and it parses my files correctly :) Thanks for the quick fix!

**Comment by adamdecaf** [comment]
Fixed in https://github.com/moov-io/bai2/pull/116

**Comment by wokkaflokka** [comment]
Would it be fine to cut a new release? `v.0.4.0` (or `v.0.3.1`)?

**Comment by adamdecaf** [comment]
Yea, I'll make a release.
