### ISSUE TITLE
Add support for variable-length BAI2 files

### ISSUE THREAD

**Issue by barszcz** [moov-io/bai2#49]
Bai2 Version: `0.1.0`

**What were you trying to do?**
I tried to use the library (as an imported Go package, calling `file.Parse`) to parse a BAI II file defined in a variable length format (see page 10 of [the spec](https://www.bai.org/docs/default-source/libraries/site-general-downloads/cash_management_2005.pdf)).

**What did you expect to see?**
I expected to see a properly parsed `file.Bai2` data structure with the fields populated appropriately.

**What did you see?**
Instead I saw a struct mostly filled with zero values. When looking at the source code I discovered that the library as currently written expects BAI files in the fixed-length format only. In fact, it's even more rigid than that, as the parser is expecting individual columns for each record type to begin at specific indices within the record, which is more rigid than the spec calls for. The correct behavior in either case would be to read the record until the next delimiter, no matter what index that appears at.

It seems I received silent failures rather than parse errors as well because the library simply swallows many errors that occur in parsing (see: nearly any call to `util.EntryParser` where the error is ignored). Many of the `Validate` methods also seem to expect specific hard-coded values, which means they aren't generally useful.

**How can we reproduce the problem?**
I can share a sample file here once I've verified it's free of any sensitive information. This should be enough to reproduce the behavior.

I'm on the Slack and am hoping to start a conversation there about making the parser more accepting as my team needs to be able to ingest variable-length BAI II files for work we're working on this quarter. We're happy to make the necessary changes and open a PR, but based on what I've heard it sounds like you may be looking to improve this library soon anyway. Let me know, thanks!

**Comment by mfdeveloper508** [comment]
@barszcz 
Thanks for reporting the issue, would you give me sample data?
