### ISSUE TITLE
Return richer domain objects from parser

### ISSUE THREAD

**Issue by barszcz** [moov-io/bai2#52]
Bai2 Version: `0.1.0` (todo update this?)

**What were you trying to do?**

This is a follow-on from https://github.com/moov-io/bai2/issues/49 and https://github.com/moov-io/bai2/pull/51

**What did you expect to see?**
Ideally the parser should return a `File` object that contains one or more `Groups`. `Groups` contain one or more `Account`s, and `Accounts` contain zero or more `TransactionDetail`s. This is consistent with the semantics of the file format as defined in [the spec](https://www.bai.org/docs/default-source/libraries/site-general-downloads/cash_management_2005.pdf).

**What did you see?**
Instead, the parser returns a `file.Bai2` object (consider renaming this to `File` for consistency). This contains a slice of `Group`s as one might expected. However, the structure is flat from here on out. Instead, a group contains a flat slice of all of its subsequent "records" (i.e. structs representing individual rows in the file). This isn't optimal because it exposes lots of details of the file format to a user who really just wants the data from it, like the header and trailer records for a group/account, as well as continuation records.

**How can we reproduce the problem?**
Call `bai2.Parse` on any valid BAI2 file.

I think we can probably approach this in two distinct phases. First, a "scanning" phase where we read each row of the file into a record struct, building up a flat slice of records. Then we can have a "parsing" phase, where we build that richer structure from the records. The result of that second phase would be what we return to a user.

Copying from my comment on the previous PR, the final file/group/account objects can probably look something like
```go
type File struct {
	// Metadata from file header
	Sender               string
	Receiver             string
	FileCreatedDate      string
	FileCreatedTime      string
	FileIdNumber         string
	PhysicalRecordLength int64 `json:",omitempty"`
	BlockSize            int64 `json:",omitempty"`
	VersionNumber        int64
	
	// Metadata from file trailer
	FileControlTotal string
	NumberOfGroups   int64
	NumberOfRecords  int64

	// Groups
	Groups []*Group
}
```
The consumer shouldn't need to be aware of the headers/trailers, so we can just collapse the data from those into the relevant model structs. We can do something similar for groups
```go
type Group struct {
	// Metadata from group header
	Receiver         string `json:",omitempty"`
	Originator       string
	GroupStatus      int64
	AsOfDate         string
	AsOfTime         string `json:",omitempty"`
	CurrencyCode     string `json:",omitempty"`
	AsOfDateModifier int64  `json:",omitempty"`

	// Metadata from group trailer
	GroupControlTotal string
	NumberOfAccounts  int64
	NumberOfRecords   int64

	// Accounts
	Accounts []*Account
}
```
and accounts
```go
type Account struct {
	// Metadata from account identifier
	AccountNumber string
	CurrencyCode  string       `json:",omitempty"`
	TypeCode      string       `json:",omitempty"`
	Amount        string       `json:",omitempty"`
	ItemCount     string       `json:",omitempty"`
	FundsType     FundsType    `json:",omitempty"` // this can be a string for first take, or we can ignore it until we get it right

	// Metadata from account trailer
	AccountControlTotal string
	NumberRecords       int64

	// Transaction Details
	TransactionDetails []*TransactionDetail
}
```

The transaction details struct would be similar. 

For a first pass, I suggest we take a stab at proper handling of continuation records, but punt on handling funds type (and the fields that come after it in transaction details). For now we can return the last few fields in a string slice or something (similar to the `Composite` thing that exists now. Proper handling of that can come in a separate PR.

**Comment by adamdecaf** [comment]
I'm a fan of this since there are only a few fields in the header/trailer.
